version: '3'

services:

  eshop-web:
    container_name: web
    image: nginx:alpine
    ports:
      - 86:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
    links:
      - eshop-php
    depends_on:
      - eshop-php
    networks:
      - net

  eshop-php:
    container_name: eshop-php
    build: docker/php
    ports:
      - "9002:9002"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      XDEBUG_MODE: ${XDEBUG_MODE}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG-}
    networks:
      - net
    extra_hosts:
      - host.docker.internal:host-gateway

  eshop-postgres:
    image: postgres:latest
    container_name: eshop-postgres
    environment:
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop
      POSTGRES_DB: eshop
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - net

  eshop-redis:
    container_name: eshop-redis
    image: redis:latest
    restart: on-failure
    ports:
      - "6398:6379"
    networks:
      - net

  eshop-zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: eshop-zoo
    container_name: eshop-zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  eshop-kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: eshop-kafka
    container_name: eshop-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://eshop-kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "eshop-zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - eshop-zoo

#  eshop-wiremock:
#    container_name: eshop-wiremock
#    image: rodolpheche/wiremock
#    volumes:
#      - ./tests/wiremock:/home/wiremock
#    ports:
#      - '8080:8080'
#    networks:
#      - net

networks:
  net:
