api_login:
    path: /eshop/api/v1/auth/login

api_refresh_token:
    path: /eshop/api/v1/auth/refresh

controllers:
    prefix: /eshop
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
